const express=require("express")
const rNrRouter=express.Router()
const auth=require("../Middleware/authentication")
const isClient=require("../Middleware/isClient")
const isFreelancer=require("../Middleware/isFreelancer")
const {tofreelancer,toclient,viewFreelancerRnR,viewClientRnR,viewFreelancerRnrByClient,viewClientRnrByFreelancer}=require("../Controller/rNrController")
rNrRouter.post("/tofreelancer/:freelancerId/:orderId",auth,isClient,tofreelancer)
rNrRouter.post("/toclient/:clientId/:orderId",auth,isFreelancer,toclient)
rNrRouter.get("/viewFreelancerRnR",auth,viewFreelancerRnR)
rNrRouter.get("/viewClientRnR",auth,viewClientRnR)
rNrRouter.get("/viewFreelancerRnrByClient/:freelancerId",auth,viewFreelancerRnrByClient)
rNrRouter.get("/viewClientRnrByFreelancer/:clientId",auth,viewClientRnrByFreelancer)
module.exports=rNrRouter