const mongoose=require("mongoose")

const gigSchema= new mongoose.Schema({
    title:{
        type:String,
        required:true,
        minlength:8,
        maxlength:1024
    },
    skills:{
        type:[String],
        required:true,
    },
    description:{
        type:String,
        minlength:10,
        maxlength:500
    },
    basic:{
        price:{
            type:Number,
            required:true
        },
        time:{
            type:String,
            required:true
        },
        detail:{
            type:String,
            minlength:5,
            maxlength:300
        },
        offerDetails:{
            type:[String],
        },
        revisions:{
            type:Number,
            required:true
        }
    },
    standard:{
        price:{
            type:mongoose.Decimal128,
            required:true
        },
        time:{
            type:String,
            required:true
        },
        detail:{
            type:String,
            minlength:5,
            maxlength:300
        },
        offerDetails:{
            type:[String],
        },
        revisions:{
            type:Number,
            required:true
        }
    },
    premium:{
        price:{
            type:mongoose.Decimal128,
            required:true
        },
        time:{
            type:String,
            required:true
        },
        detail:{
            type:String,
            minlength:5,
            maxlength:300
        },
        offerDetails:{
            type:[String],
        },
        revisions:{
            type:Number,
            required:true
        }
    },
    file:{
        type:[String],
    },
})

const Gig= mongoose.model("Gig",gigSchema)

module.exports=Gig