const express=require("express")
const orderRouter=express.Router()
const verifyuserloggedIn= require("../Middleware/authentication")
const isClient =require("../Middleware/isClient")
const isFreelancer=require("../Middleware/isFreelancer")
const arrayUpload=require("../Middleware/multer")
const {placeOrder,deliverOrder,viewOrdersByClient,viewOrdersByFreelancer,viewSpecificOrder,sendForRevisions,acceptOrder}=require("../Controller/OrderController")
orderRouter.post("/placeOrder/:freelancerId",verifyuserloggedIn,isClient,arrayUpload,placeOrder)
orderRouter.post("/deliverOrder/:id",verifyuserloggedIn,isFreelancer,arrayUpload,deliverOrder)
orderRouter.get("/viewOrdersByClient",verifyuserloggedIn,isClient,viewOrdersByClient)
orderRouter.get("/viewOrdersByFreelancer",verifyuserloggedIn,isFreelancer,viewOrdersByFreelancer)
orderRouter.get('/viewSpecifcOrder/:orderId',verifyuserloggedIn,viewSpecificOrder)
orderRouter.put('/sendForRevisions',verifyuserloggedIn,isClient,sendForRevisions)
orderRouter.put('/acceptOrder/:orderId',verifyuserloggedIn,isClient,acceptOrder)

module.exports =orderRouter